name: Token

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
jobs:
    test:
      name: Run Unit Tests
      runs-on: ubuntu-18.04
      
      steps:
        - name: test
          env:
            TOKEN: ${{ secrets.TOKEN }}
          run: echo $TOKEN
